Feature lift intake
ViperbotsValor6800/FRC-6800-2021-code pull request #17
Opened 2021-01-05 20:53 UTC by AntarcticaByToto

Intake and Lift state machines.
still need CAN, PWM, DIO IDs

2021-01-10 02:44 UTC, mray190 requested changes
See all of the comments. Note that the lift only needs 1 motor now

2021-01-10 02:44 UTC, mray190 commented on Competition/src/main/cpp/subsystems/Lift.cpp
> +    rightMotor.SetIdleMode(rev::CANSparkMax::IdleMode::kCoast);
dont need

2021-01-10 02:44 UTC, mray190 commented on Competition/src/main/cpp/subsystems/Lift.cpp
> +                        rightMotor{LiftConstants::RIGHT_CAN_ID, rev::CANSparkMax::MotorType::kBrushless},
dont need

2021-01-10 02:44 UTC, mray190 commented on Competition/src/main/cpp/subsystems/Lift.cpp
> +    rightMotor.SetInverted(false);
dont need

2021-01-10 02:44 UTC, mray190 commented on Competition/src/main/cpp/subsystems/Lift.cpp
> +    if (operatorController->GetBumper(frc::GenericHID::kRightHand)) {
2 things:
1. This needs to be the right trigger not the bumper
2. Since this is a trigger, you will need to compare a double rather than a boolean. For example, you need to say greater than 0.2 (dont want to do greater than 0 cause deadband will randomly trigger it)

2021-01-10 02:44 UTC, mray190 commented on Competition/src/main/cpp/subsystems/Lift.cpp
> +        state.power = -1 * liftTable->GetEntry("Lift Speed").GetDouble(0.0);
We should make the -1 a variable in the class definition so we can flip the orientation quickly. We currently do not know if -1 or 1 is retract or extend

2021-01-10 02:44 UTC, mray190 commented on Competition/src/main/cpp/subsystems/Lift.cpp
> +        state.power = -1 * liftTable->GetEntry("Lift Speed").GetDouble(0.0);
This line needs to be in assignOutputs. Setting the power in the assessInputs is no bueno. In your flowchart, you set the power in assignOutputs and not assessInputs

2021-01-10 02:44 UTC, mray190 commented on Competition/src/main/cpp/subsystems/Lift.cpp
> +            state.power = liftTable->GetEntry("Lift Speed").GetDouble(0.0);
same thing as above - this line needs to be in assignOutputs

2021-01-10 02:44 UTC, mray190 commented on Competition/src/main/cpp/subsystems/Lift.cpp
> +            state.power = liftTable->GetEntry("Lift Speed").GetDouble(0.0);
Multiply by a variable that is declared in the class definition. Can be -1 or 1 like before, and will be determined once we figure out what direction the motor goes IRL

2021-01-10 02:44 UTC, mray190 commented on Competition/src/main/cpp/subsystems/Lift.cpp
> +            state.target = state.power; //set motion profiling target to the output of the motion profiling.
Motion profile code does not go here

2021-01-10 02:44 UTC, mray190 commented on Competition/src/main/cpp/subsystems/Lift.cpp
> +            if (state.liftState == LiftState::RETRACT) {
Contents of this if statement need to stay here, but the if statement itself is not needed

2021-01-10 02:44 UTC, mray190 commented on Competition/src/main/cpp/subsystems/Lift.cpp
> +                leftMotor.Set(state.power);
Rename power to something more meaningful

2021-01-10 02:44 UTC, mray190 commented on Competition/src/main/cpp/subsystems/Lift.cpp
> +                leftMotor.Set(state.power);
Pull down the power logic in assessInputs into this block of code

2021-01-10 02:44 UTC, mray190 commented on Competition/src/main/cpp/subsystems/Lift.cpp
> +                rightMotor.Set(state.power);
don't need right motor anymore

2021-01-10 02:44 UTC, mray190 commented on Competition/src/main/cpp/subsystems/Lift.cpp
> +                leftMotor.Set(state.target);
move down motion profile code in assessInputs down into this function

2021-01-10 02:44 UTC, mray190 commented on Competition/src/main/include/Constants.h
> +    constexpr static int RIGHT_CAN_ID = 0; //Need CAN ID
don't need anymore

2021-01-10 02:44 UTC, mray190 commented on Competition/src/main/include/Constants.h
> +    constexpr static int COMPRESSOR_PCM_ID = 0;
this is un-needed.
If we need to modify compressor stuff in the future, we will move it into a separate subsystem

2021-01-10 02:44 UTC, mray190 commented on Competition/src/main/include/subsystems/Intake.h
> +        frc::Compressor compressor;
not needed

2021-01-10 02:44 UTC, mray190 commented on Competition/src/main/cpp/subsystems/Intake.cpp
> +                        compressor{IntakeConstants::COMPRESSOR_PCM_ID},
not needed

2021-01-10 02:44 UTC, mray190 commented on Competition/src/main/include/Constants.h
> +    constexpr static int RIGHT_SOLENOID_FORWARD_PCM_CAN_ID = 0;  //Need PCM CAN ID
not needed

2021-01-10 02:44 UTC, mray190 commented on Competition/src/main/include/Constants.h
> +    constexpr static int RIGHT_SOLENOID_REVERSE_PCM_CAN_ID = 0;  //Need PCM CAN ID
not needed

2021-01-10 02:44 UTC, mray190 commented on Competition/src/main/include/subsystems/Intake.h
> +        frc::DoubleSolenoid rightSolenoid;
we will add a y connector to the pneumatic line so that a single solenoid is used to control the intake. the right solenoid is not needed

2021-01-10 02:44 UTC, mray190 commented on Competition/src/main/cpp/subsystems/Intake.cpp
> +                        rightSolenoid{IntakeConstants::RIGHT_SOLENOID_FORWARD_PCM_CAN_ID,IntakeConstants::RIGHT_SOLENOID_REVERSE_PCM_CAN_ID} {
not needed

2021-01-10 02:44 UTC, mray190 commented on Competition/src/main/cpp/subsystems/Intake.cpp
> +        state.power = intakeTable->GetEntry("Intake Speed").GetDouble(0.0);
move code down into assignOutputs

2021-01-10 02:44 UTC, mray190 commented on Competition/src/main/cpp/subsystems/Intake.cpp
> +        if (operatorController->GetBButton()) {
instead of `else` and THEN `if`, make it an `else if`

2021-01-11 23:46 UTC, AntarcticaByToto commented on Competition/src/main/cpp/subsystems/Lift.cpp
> +        state.power = -1 * liftTable->GetEntry("Lift Speed").GetDouble(0.0);
i've changed the power to 2 smart dashboard variables. One for power in one for power out as discussed in the meeting. does that work or should i still having something in constants.

2021-01-12 00:05 UTC, AntarcticaByToto commented on Competition/src/main/include/Constants.h
> +    constexpr static int RIGHT_CAN_ID = 0; //Need CAN ID
can you explain why I don't need the can ids?

2021-01-12 00:06 UTC, AntarcticaByToto commented on Competition/src/main/include/Constants.h
> +    constexpr static int COMPRESSOR_PCM_ID = 0;
i put it here because i have to specify what port the compressor is when instantiating the compressor.

2021-01-12 00:08 UTC, AntarcticaByToto commented on Competition/src/main/cpp/subsystems/Lift.cpp
> +                        rightMotor{LiftConstants::RIGHT_CAN_ID, rev::CANSparkMax::MotorType::kBrushless},
i don't understand why i don't need to call the constructors for these. They don't have a default constructor.

2021-01-12 00:08 UTC, AntarcticaByToto commented on Competition/src/main/cpp/subsystems/Intake.cpp
> +                        compressor{IntakeConstants::COMPRESSOR_PCM_ID},
i don't understand why i don't need to call the constructors for these. They don't have a default constructor.

2021-01-12 01:39 UTC, mray190 commented on Competition/src/main/cpp/subsystems/Lift.cpp
> +        state.power = -1 * liftTable->GetEntry("Lift Speed").GetDouble(0.0);
That part is fine. But the -1 is what industry calls "magic numbers". That -1 should be saved in a variable in constants, as a member variable of the class, or also in the smart dashboard

2021-01-12 01:40 UTC, mray190 commented on Competition/src/main/include/Constants.h
> +    constexpr static int RIGHT_CAN_ID = 0; //Need CAN ID
You need the CAN ID. You don't need both though - just 1 now

2021-01-12 01:40 UTC, mray190 commented on Competition/src/main/include/Constants.h
> +    constexpr static int COMPRESSOR_PCM_ID = 0;
But why do you need to instantiate the compressor to begin with?

2021-01-12 01:40 UTC, mray190 commented on Competition/src/main/cpp/subsystems/Intake.cpp
> +                        compressor{IntakeConstants::COMPRESSOR_PCM_ID},
Just the compressor is un-needed. The motor is needed

2021-01-18 17:58 UTC, janhelgeson commented on Competition/src/main/include/Constants.h
> +    constexpr static int COMPRESSOR_PCM_ID = 0;
Removed Compressor references.

2021-01-18 17:59 UTC, janhelgeson commented on Competition/src/main/include/Constants.h
> +    constexpr static int RIGHT_SOLENOID_FORWARD_PCM_CAN_ID = 0;  //Need PCM CAN ID
Removed reverse solenoid - only need 1.

2021-01-18 18:36 UTC, janhelgeson commented on Competition/src/main/cpp/subsystems/Intake.cpp
> +        solenoid.Set(frc::Solenoid::Value::kReverse);
@AntarcticaByToto  Can you verify the implementation of single solenoids?

2021-01-30 03:08 UTC, merged