Feature Hopper
ViperbotsValor6800/FRC-6800-2021-code pull request #6
Opened 2020-08-21 14:48 UTC by CooperNelson16

### General  Concept
- Chooses between 3 states
1. Disabled
2. Forward
3. Reverse

- Takes input from driver and operator controllers to assign states
- Outputs power to hopper and throat motors

2020-08-21 15:11 UTC, rohitchawla28 requested changes

2020-08-21 15:11 UTC, rohitchawla28 commented on Competition/src/main/cpp/Hopper.cpp
> +    if (std::abs(driverController->GetRawButton(9))) {
You can use the controller->Get(button name) instead if you want, so we don't have random number. or make a constant or something.

2020-08-21 15:11 UTC, rohitchawla28 commented on Competition/src/main/cpp/Hopper.cpp
> +
I think the set powers for motors should be outside the else condition.

2020-08-21 15:11 UTC, rohitchawla28 commented on Competition/src/main/cpp/Hopper.cpp
> +
If you want to use both controllers, you'll have to initialize both in the constructor. So like, same way you have operator controller being set, would do same with driver controller. so you would need another parameter as well.

2020-08-21 15:11 UTC, rohitchawla28 commented on Competition/src/main/cpp/Hopper.cpp
> +
Do you have a resetState() method?

2020-08-21 15:11 UTC, rohitchawla28 commented on Competition/src/main/cpp/Hopper.cpp
> +
Currently, I think you have some state logic errors. It looks like the hopper will always run if you press the forward or the reverse button because you don't set the state to disabled or have some other workaround for setting 0 power.

2020-08-31 20:28 UTC, mray190 approved these changes
LGTM

2020-08-31 20:30 UTC, merged