Feature lift
ViperbotsValor6800/FRC-6800-2021-code pull request #7
Opened 2020-08-21 17:23 UTC by AntarcticaByToto

2020-08-22 23:29 UTC, rohitchawla28 commented on Competition/src/main/cpp/Lift.cpp
> +   if (state.liftState == LiftState::EXTEND) {
I think we used servo.Set() last year, were you intending to change that?

2020-08-22 23:31 UTC, rohitchawla28 commented on Competition/src/main/include/Constants.h
> +
these are the constants for the .Set method. If you are gonna use the .SetAngle it would be diff

2020-09-08 00:56 UTC, mray190 requested changes

2020-09-08 00:56 UTC, mray190 commented on Competition/src/main/cpp/Lift.cpp
> +Lift::Lift() : liftMtrLeft{LiftConstants::VICTOR_ID_LEFT_Lift},
Call the ValorSubsystem constructor in the intializer list. See other subsystems for an example

2020-09-08 00:56 UTC, mray190 commented on Competition/src/main/cpp/Lift.cpp
> +    initLift();
Don't need to call init if you call the ValorSubsystem constructor as it will call init for you

2020-09-08 00:56 UTC, mray190 commented on Competition/src/main/cpp/Lift.cpp
> +void Lift::initLift() {
rename to `init`. The ValorSubsystem that this implements has an init method that you need to override

2020-09-08 00:56 UTC, mray190 commented on Competition/src/main/cpp/Lift.cpp
> +    resetState();
need to implement this function in the Lift class. Fill the function with setting the motor outputs in the state member struct to 0

2020-09-08 00:56 UTC, mray190 commented on Competition/src/main/cpp/Lift.cpp
> +        state.liftState = LiftState::DISABLED;
Should set the right joystick Y values to 0 in the else case - otherwise your joystick values will always sit outside the deadband

2020-09-08 00:56 UTC, mray190 commented on Competition/src/main/cpp/Lift.cpp
> +   if (state.liftState == LiftState::EXTEND) {
@rohitchawla28 this looks fixed yes?

2020-09-08 00:56 UTC, mray190 commented on Competition/src/main/include/Lift.h
> +        void initLift();
change to `init`

2020-09-08 00:56 UTC, mray190 commented on Competition/src/main/include/Lift.h
> +        //void resetState();
Uncomment and implement

2020-09-16 17:16 UTC, mray190 requested changes

2020-09-16 17:16 UTC, mray190 commented on Competition/src/main/cpp/Lift.cpp
> +    resetState();
Still has no implementation - hence the CI failure

2020-12-10 01:32 UTC, closed without merging